### ISSUE TITLE
你好，请问ValueError: setting an array element with a sequence. 怎么解决

### ISSUE THREAD

**Issue by wang-325** [Powercoder64/DDCN_SRM#1]
(mstct) PS E:\DDCN_SRM-main> python .\run_script_OAD.py
use gpu
start testing DDCN on Observation Ratio = 100%...
Traceback (most recent call last):
  File ".\run_script_OAD.py", line 75, in <module>
    result_100, label_100 = tester_100.test()  # loading DDCN model
  File "E:\DDCN_SRM-main\DDCN_testing_OAD_100_per.py", line 76, in test
    outputs = np.array(outputs)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (20,) + inhomogeneous part.

**Comment by Powercoder64** [comment]
Which version of Pytorch are you using? I recommend using Pytorch 1.7 to avoid any issues regarding the dataloader!
